spring:
  application:
    name: queue_management_system

  mvc:
    hiddenmethod:
      filter:
        enabled: true

jwt:
  expired:
    days: 7

group:
  capacity: 5
  timeout: 1
  confirm:
    percent: 0.5
