spring:
  application:
    name: queue_management_system

  mvc:
    hiddenmethod:
      filter:
        enabled: true

jwt:
  secret: ${JWT_SECRET}
  expired-days: ${JWT_EXPIRED_DAYS}


app:

  group-capacity: ${GROUP_CAPACITY}
  group-timeout: ${GROUP_TIMEOUT}
  group-confirm-percent: ${GROUP_CONFIRM_PERCENT}

telegram:
  bot-token: ${TG_BOT_TOKEN}
  bot-username: ${TG_BOT_USERNAME}
  chat-id: ${TG_CHAT_ID}
  chat-thread-id: ${TG_CHAT_THREAD_ID}


