spring:
  application:
    name: queue_management_system

  mvc:
    hiddenmethod:
      filter:
        enabled: true

jwt:
  expired:
    days: 7

app:
  group-capacity: 5
  group-timeout: 1
  group-confirm-percent: 0.5
