name: Deploy Backend

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin

      - name: Install Maven
        run: sudo apt update && sudo apt install -y maven

      - name: Build backend JAR
        run: mvn clean package -DskipTests=true -Dmaven.test.skip=true

      - name: Clear old files
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: '22123'
          script: |
            cd /opt/QMS/backend
            rm -rf *.jar docker-compose.yml

      - name: Copy docker-compose.yml to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: '22123'
          source: "docker-compose.yml"
          target: "/opt/QMS/backend/"

      - name: Copy JAR to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: '22123'
          source: "target/*.jar"
          target: "/opt/QMS/backend/"

      - name: "SSH: Deploy"
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: '22123'
          script: |
            cd /opt/QMS/backend
            docker compose down
            docker compose up -d --build