name: Deploy Backend

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin

      - name: Clear old files
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: '22123'
          script: |
            cd /opt/QMS/backend
            find . -mindepth 1 \
              -not -name '.env' \
              -not -name 'database.env' \
              -delete

      - name: Archive project
        run: tar czf project.tar.gz src .mvn mvnw Dockerfile docker-compose.yml pom.xml

      - name: Copy archive
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: '22123'
          source: "project.tar.gz"
          target: "/opt/QMS/backend"

      - name: Extract on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: '22123'
          script: |
            cd /opt/QMS/backend
            tar xzf project.tar.gz
            rm project.tar.gz

      - name: "Check copied files"
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: '22123'
          script: |
            cd /opt/QMS/backend
            ls -la

      - name: "SSH: Deploy"
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: '22123'
          script: |
            cd /opt/QMS/backend
            docker compose down
            docker compose up -d --build